version: "3.8"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mysql:
    image: mysql
    ports:
      - 3030:3306
    volumes:
      - db_data:/var/lib/mysql/
      - /etc/localtime:/etc/localtime:ro
      - ./mysql/conf.d/:/etc/mysql/conf.d/
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
volumes:
  db_data:
  redis:
    driver: local
